# Generated by Django 3.2.6 on 2021-08-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=200, null=True)),
                ('user_image', models.CharField(max_length=500, null=True)),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('birthday', models.DateField(null=True)),
                ('kakao_number', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
