<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-08-18 23:15
=======
# Generated by Django 3.2.6 on 2021-08-18 17:33
>>>>>>> 0ea6823 (EDIT: model작성)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, null=True)),
                ('score', models.PositiveIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
<<<<<<< HEAD
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
=======
                ('image', models.CharField(max_length=500)),
>>>>>>> 0ea6823 (EDIT: model작성)
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
