# Generated by Django 3.2.6 on 2021-08-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='review',
            name='key',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
