# Generated by Django 3.2.6 on 2021-08-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210825_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
