# Generated by Django 3.2.6 on 2021-08-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_image'),
        ('reviews', '0003_auto_20210825_1528'),
    ]

    operations = [
    ]
