# Generated by Django 3.2.6 on 2021-08-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='nane',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='coordinate_x',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='coordinate_y',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='custom_text',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fontcolor',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fontstyle',
            name='style',
            field=models.CharField(max_length=30),
        ),
    ]
