# Generated by Django 3.2.6 on 2021-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fontcolor',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fontstyle',
            name='style',
            field=models.CharField(max_length=30),
        ),
    ]
