# Generated by Django 3.2.6 on 2021-08-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210820_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='nane',
            new_name='name',
        ),
    ]
