# Generated by Django 3.2.6 on 2021-08-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_nane_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='coordinate_x',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='coordinate_y',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='custom_text',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
