# Generated by Django 3.2.6 on 2021-08-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210824_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='product_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productoption'),
        ),
    ]
