# Generated by Django 3.2.6 on 2021-08-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210823_1536'),
        ('products', '0004_auto_20210824_1555'),
    ]

    operations = [
    ]
