# Generated by Django 3.2.6 on 2021-08-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210824_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
