# Generated by Django 3.2.6 on 2021-08-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210824_1659'),
        ('products', '0006_merge_20210825_1718'),
    ]

    operations = [
    ]
